### ISSUE TITLE
Could I use it with `colleciton2, simple schema, autoform`?

### ISSUE THREAD

**Issue by thearabbit** [tamino-martinius/meteor-smart-record#2]
Could I use it with `colleciton2, simple schema, autoform`?

**Comment by tamino-martinius** [comment]
Hi thanks for your feedback,
this package is currently in a very early stage and not checked for compatibility to other packages.
As soon as the basement of this package is solid i'll check how to use this with the most common packages.
The simple schema package is very interesting - i maybe integrate this to define the schema.

**Comment by thearabbit** [comment]
Thanks for your reply.
Now I use `Auto Form, Simple Schema and Collection2`, so I need support its.
Waiting you...

**Comment by tamino-martinius** [comment]
`AutoForm` and `simple schema` will come with one of the next versions. See this branch for the current WIP: https://github.com/tamino-martinius/meteor-smart-record/tree/simple-schema

**Comment by tamino-martinius** [comment]
The newest version (`0.1.0`) now uses `simple-schema` for schema definitions. I also forked `autoform` to work with this package see [zaku:smart-form package](https://github.com/tamino-martinius/meteor-smart-form)

**Comment by thearabbit** [comment]
Great I will check soon.
