### ISSUE TITLE
schema functions and nested fields?

### ISSUE THREAD

**Issue by Sivli-Embir** [tamino-martinius/meteor-smart-record#3]
What is your plan for extending the schema? I very much like were you are going but I worry about having a schema that is limited. 

Will you allow functions as a validation type? What about nested fields. 

I have been using my own modal system for a while but yours is much better. That said I would hesitaite to give up my schema system: https://github.com/Meteor-Reaction/shadow-models

**Comment by tamino-martinius** [comment]
The schema currently allows an function or an array of functions as validator.
But cause 2 of 2 issues are mentioning the schema i'll switch to simple schema for the schema definitions.
See this branch for the current WIP https://github.com/tamino-martinius/meteor-smart-record/tree/simple-schema

**Comment by tamino-martinius** [comment]
The newest version (`0.1.0`) now uses [simple-schema](https://github.com/aldeed/meteor-simple-schema) for schema definitions. I also forked [autoform](https://github.com/aldeed/meteor-autoform) to work with this package see [zaku:smart-form package](https://github.com/tamino-martinius/meteor-smart-form)
