### ISSUE TITLE
Duplicate declaration "scope"

### ISSUE THREAD

**Issue by Sivli-Embir** [tamino-martinius/meteor-smart-record#5]
As of METEOR@1.3-beta.11:
`packages/zaku:smart-record/lib/smart_model.js:288:8: /packages/zaku:smart-record/lib/smart_model.js: Duplicate declaration "scope"`

Not sure if this is going to be the standard but you can't `let scope` in a class method of `scope`. A simple `let _scope` does the trick.

**Comment by Sivli-Embir** [comment]
Also see: `...563:8 ... Duplicate declaration "collection"`

**Comment by tamino-martinius** [comment]
Already fixed in branch [0.2.0](https://github.com/tamino-martinius/meteor-smart-record/tree/version-0.2.0).
Will released as soon as Meteor 1.3 is released - comes also with some breaking changes, cause static getters are now available with 1.3

**Comment by tamino-martinius** [comment]
@Kestanous Just released v0.2.0 with Meteor@1.3 support
